-- Esquema de Base de Datos: Ortho-Cardio CRM Búnker
-- Optimizado para PostgreSQL (Supabase)

-- Extensiones
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

-- Tabla de Contactos (Prospectos y Clientes)
CREATE TABLE IF NOT EXISTS contacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    phone_number TEXT UNIQUE NOT NULL,
    hospital TEXT,
    is_ai_active BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'PENDING',
    followup_draft TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_interaction TIMESTAMPTZ DEFAULT NOW()
);


-- Tabla de Mensajes (Historial Omnicanal)
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_phone TEXT REFERENCES contacts(phone_number) ON DELETE CASCADE,
    sender_type TEXT CHECK (sender_type IN ('user', 'ai', 'human')),
    content TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB
);

-- Habilitar Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
ALTER PUBLICATION supabase_realtime ADD TABLE contacts;

-- Tabla de Catálogo de Precios (Inventario Maestro)
CREATE TABLE IF NOT EXISTS price_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    description TEXT,
    price DECIMAL(12, 2),
    hospital TEXT,
    alternative_code TEXT,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('spanish', description || ' ' || code)) STORED
);

-- Tabla de Conocimiento Clínico (RAG Vectorial)
CREATE TABLE IF NOT EXISTS clinical_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code TEXT REFERENCES price_list(code) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding vector(768), -- Dimensión para text-embedding-004 de Google
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_messages_contact_phone ON messages(contact_phone);
CREATE INDEX IF NOT EXISTS idx_contacts_last_interaction ON contacts(last_interaction DESC);
CREATE INDEX IF NOT EXISTS idx_price_list_code ON price_list(code);
CREATE INDEX IF NOT EXISTS idx_price_list_search ON price_list USING GIN(search_vector);
CREATE INDEX IF NOT EXISTS idx_clinical_knowledge_embedding ON clinical_knowledge USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_clinical_knowledge_product ON clinical_knowledge(product_code);

-- Habilitar Realtime adicional
ALTER PUBLICATION supabase_realtime ADD TABLE price_list;
ALTER PUBLICATION supabase_realtime ADD TABLE clinical_knowledge;
